// The map through the engine. One seed in; every theme in docs/map.md out, each key holding
// the engine's value for the recorded name in light and in dark. This file projects: it never
// parses CSS and never invents a value. `dist/theme.ts` records, beside each theme, the
// engine name every key came from, which is what the check verifies.
import { mkdirSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import {
  resolveTheme,
  themeTokens,
  interactionTokens,
  INTERACTION_FAMILIES,
  interactionTintName,
} from 'okchroma'
import { SEED, BRAND, PROFILE } from './seed.ts'
import { BASE, FAMILY_EDGE, TIERS, INPUT, DIALOG, type KeyMap } from './map.ts'

type Mode = 'light' | 'dark'
const MODES: readonly Mode[] = ['light', 'dark']

// ── 1. the engine's emission as one object per mode ───────────────────────────
const theme = resolveTheme({ primaryHex: SEED, name: BRAND, deriveSecondary: true, contrastProfile: PROFILE })
const all = interactionTokens(
  themeTokens({
    slug: BRAND,
    displayName: 'PoC',
    brand: theme.themed,
    secondary: theme.secondary?.scale ?? null,
    secondaryStyle: theme.secondary?.style,
    contrastProfile: PROFILE,
  }),
)

// React Native's color parser reads `rgba(r, g, b, a)` and not the slash grammar the
// engine's system tokens use. Same color, one grammar, so both platforms parse it.
const normalize = (v: string): string =>
  v.replace(/^rgba?\(\s*([\d.]+)\s+([\d.]+)\s+([\d.]+)\s*\/\s*([\d.%]+)\s*\)$/, (_m, r, g, b, a) => {
    const alpha = String(a).endsWith('%') ? Number(String(a).slice(0, -1)) / 100 : Number(a)
    return `rgba(${r}, ${g}, ${b}, ${alpha})`
  })

const isColor = (v: string) => /^(#|rgb|rgba|hsl|oklch|color\(|transparent)/.test(v)
const colorNames = all.names.filter(n => isColor(all.light[n]))

const resolve = (name: string, mode: Mode): string => {
  if (name === 'transparent') return name
  const v = all[mode][name]
  if (v === undefined || String(v).includes('undefined')) throw new Error(`the engine emits no ${mode} value for ${name}`)
  if (!isColor(v)) throw new Error(`${name} is not a color (${v}); the map may only name colors`)
  return normalize(v)
}

// ── 2. expand the map per family ─────────────────────────────────────────────
const expand = (map: KeyMap, family: string): KeyMap =>
  Object.fromEntries(
    Object.entries(map).map(([k, name]) => [
      k,
      name.replaceAll('<family>', family).replaceAll('<tint>', interactionTintName(family)),
    ]),
  )

/** theme name -> key -> engine name; the transcription the check reads back */
const sources: Record<string, KeyMap> = {}
for (const mode of MODES) {
  // the base carries the kit's keys and, under its own name, every color the engine emits
  sources[mode] = { ...Object.fromEntries(colorNames.map(n => [n, n])), ...BASE }
  for (const family of INTERACTION_FAMILIES) {
    sources[`${mode}_${family}`] = expand(FAMILY_EDGE, family)
    for (const tier of ['solid', 'subtle', 'hint', 'outline'] as const) {
      sources[`${mode}_${family}_${tier}`] = expand(TIERS[tier], family)
    }
  }
  for (const [name, map] of Object.entries({ ...INPUT, ...DIALOG })) sources[`${mode}_${name}`] = map
}

const themes: Record<string, Record<string, string>> = {}
for (const [themeName, map] of Object.entries(sources)) {
  const mode = themeName.startsWith('dark') ? 'dark' : 'light'
  themes[themeName] = Object.fromEntries(Object.entries(map).map(([k, name]) => [k, resolve(name, mode)]))
}

// ── 3. write ──────────────────────────────────────────────────────────────────
const here = dirname(fileURLToPath(import.meta.url))
const dist = join(here, '..', 'dist')
mkdirSync(dist, { recursive: true })

const disabledOpacity = Number(all.light['disabled-opacity'])
if (!Number.isFinite(disabledOpacity)) throw new Error('the engine emits no disabled-opacity')

const out = [
  '// GENERATED by packages/theme/src/build.ts from docs/map.md through okchroma. Do not edit.',
  `// seed ${SEED}, brand ${BRAND}, lane ${PROFILE}`,
  `export const SEED = ${JSON.stringify(SEED)}`,
  `export const themes = ${JSON.stringify(themes, null, 2)} as const`,
  '/** theme -> key -> the engine name the value came from */',
  `export const sources = ${JSON.stringify(sources, null, 2)} as const`,
  `export const families = ${JSON.stringify([...INTERACTION_FAMILIES])} as const`,
  `export const disabledOpacity = ${disabledOpacity}`,
  '',
].join('\n')
writeFileSync(join(dist, 'theme.ts'), out)

const themeCount = Object.keys(themes).length
console.log(`themes: ${themeCount} (${MODES.length} modes x ${themeCount / MODES.length}), ${colorNames.length} engine colors on the base, seed ${SEED}`)
