// The Figma check, the roster check's twin: prints the use_figma script that compares the file
// against the repo. For every okchroma name the stylesheets read, the script finds the variable
// at its mapped path and resolves it in Light and in Dark; the values must equal what tokens.css
// gives the name in each mode. For every foundation, the variable must exist with the value the
// source gives. It returns what is missing and what disagrees; nothing is written.
//
//   npm run check:figma > /tmp/check.js     then paste into use_figma and read the return
//
// A summary of the expectations goes to stderr so the mapping can be read without Figma.
import { cssTables, resolveCss, namesRead, figmaPath, foundationVars, disabledOpacityVar, RESOLVER_JS } from './lib.ts'

const t = cssTables()
const colors = namesRead(t)
  .filter((css) => css !== '--disabled-opacity')
  .map((css) => ({ css, figma: figmaPath(css), light: resolveCss(css, 'light', t), dark: resolveCss(css, 'dark', t) }))
const unmapped = colors.filter((c) => !c.figma)
if (unmapped.length) {
  console.error(`check:figma: no mapping rule for ${unmapped.map((c) => c.css).join(', ')}`)
  process.exit(1)
}
const values = [...foundationVars(), disabledOpacityVar()].map((v) => ({ css: v.css, figma: v.name, type: v.type, value: v.value }))

console.error(`check:figma: ${colors.length} okchroma colors and ${values.length} foundation values expected`)
for (const c of colors) console.error(`  ${c.css.padEnd(30)} ${c.figma!.padEnd(34)} ${c.light.padEnd(12)} ${c.dark}`)

process.stdout.write(`// GENERATED by scripts/figma/check.ts. Read-only. Paste into use_figma.
const EXPECT_COLORS = ${JSON.stringify(colors)}
const EXPECT_VALUES = ${JSON.stringify(values)}
${RESOLVER_JS}
const missing = []
const mismatched = []
let ok = 0
for (const e of EXPECT_COLORS) {
  const v = byName.get(e.figma)
  if (!v) { missing.push(e.figma + ' (' + e.css + ')'); continue }
  const got = { light: resolve(v, 'Light'), dark: resolve(v, 'Dark') }
  if (got.light !== e.light || got.dark !== e.dark) mismatched.push({ css: e.css, figma: e.figma, expect: { light: e.light, dark: e.dark }, got, web: v.codeSyntax?.WEB ?? '' })
  else ok++
}
const missingValues = []
for (const e of EXPECT_VALUES) {
  const v = byName.get(e.figma)
  if (!v) { missingValues.push(e.figma); continue }
  const got = v.valuesByMode[collById.get(v.variableCollectionId).modes[0].modeId]
  // Figma stores a FLOAT as a 32-bit float, so 12.8 reads back as 12.800000190734863
  const same = typeof e.value === 'number' ? Math.abs(Number(got) - e.value) < 1e-4 : String(got) === String(e.value)
  if (!same) mismatched.push({ css: e.css, figma: e.figma, expect: e.value, got })
  else ok++
}
const webOff = EXPECT_COLORS.map((e) => byName.get(e.figma)).filter(Boolean).filter((v) => v.codeSyntax?.WEB && !/^var\\(--/.test(v.codeSyntax.WEB)).length
return { ok, missing, missingValues, mismatched, codeSyntaxNotVar: webOff, collections: collections.map((c) => c.name + ' [' + c.modes.map((m) => m.name).join('/') + ']') }
`)
